### ISSUE TITLE
help 

### ISSUE THREAD

**Issue by Zezhon** [geomorphR/gmShiny#2]
An error occurs when I open my image file in gmshiny is "Error in Event Expression: object 'temp_LMs' not found; Call began: `<reactive:lms_rx>`(...)". how do i treat that?

**Comment by deanadams** [comment]
Jin,

gmShiny has input options for various data files, not original images. One must digitize those first.

Dean

Dr. Dean C. Adams (he/him)
Distinguished Professor of Evolutionary Biology
Director of Graduate Education, EEB Program
Department of Ecology, Evolution, and Organismal Biology
Iowa State University
https://faculty.sites.iastate.edu/dcadams/
phone: 515-294-3834

From: Zezhong Jin ***@***.***>
Sent: Friday, April 15, 2022 11:52 PM
To: geomorphR/gmShiny ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [geomorphR/gmShiny] help (Issue #2)


An error occurs when I open my image file in gmshiny is "Error in Event Expression: object 'temp_LMs' not found; Call began: <reactive:lms_rx>(...)". how do i treat that?

**Comment by Zezhon** [comment]
Dear Dr. Dean


Thank you for your help. That's very useful!


Best wishes.


Jin



---Original---
From: "Dean ***@***.***&gt;
Date: Mon, Apr 18, 2022 01:04 AM
To: ***@***.***&gt;;
Cc: "Zezhong ***@***.******@***.***&gt;;
Subject: Re: [geomorphR/gmShiny] help  (Issue #2)




 Jin, 
 
 gmShiny has input options for various data files, not original images. One must digitize those first. 
 
 Dean 
 
 Dr. Dean C. Adams (he/him) 
 Distinguished Professor of Evolutionary Biology 
 Director of Graduate Education, EEB Program 
 Department of Ecology, Evolution, and Organismal Biology 
 Iowa State University 
 https://faculty.sites.iastate.edu/dcadams/ 
 phone: 515-294-3834 
 
 From: Zezhong Jin ***@***.***&gt; 
 Sent: Friday, April 15, 2022 11:52 PM 
 To: geomorphR/gmShiny ***@***.***&gt; 
 Cc: Subscribed ***@***.***&gt; 
 Subject: [geomorphR/gmShiny] help (Issue #2) 
 
 
 An error occurs when I open my image file in gmshiny is "Error in Event Expression: object 'temp_LMs' not found; Call began: <reactive:lms_rx&gt;(...)". how do i treat that?
